<script setup>
import { computed, onMounted, ref } from 'vue'
import { ArrowRight, Eye, GraduationCap, Star } from 'lucide-vue-next'
import WhatsAppIcon from '../../components/WhatsAppIcon.vue'
import { RouterLink } from 'vue-router'
import AdminPageHeader from '../../components/admin/AdminPageHeader.vue'
import AdminState from '../../components/admin/AdminState.vue'
import { getAdminCourses, getAttendances } from '../../services/adminApi'

const loading = ref(true); const error = ref(''); const courses = ref([]); const clicks = ref(null)
const publishedCount = computed(() => courses.value.filter((course) => course.is_published).length)
const featuredCount = computed(() => courses.value.filter((course) => course.is_featured).length)
onMounted(async () => { try { const [courseData, clickData] = await Promise.all([getAdminCourses({ per_page: 8 }), getAttendances({ per_page: 5 })]); courses.value = courseData.data; clicks.value = clickData } catch (requestError) { error.value = requestError.message } finally { loading.value = false } })
</script>

<template><AdminPageHeader title="Visão geral" description="Acompanhe o que está acontecendo no catálogo de cursos." /><AdminState v-if="loading" message="Carregando indicadores…" /><AdminState v-else-if="error" type="error" :message="error" /><template v-else><section class="admin-stat-grid"><article><span class="stat-icon blue"><GraduationCap :size="20" /></span><div><p>Cursos cadastrados</p><strong>{{ courses.length }}</strong><small>na página atual</small></div></article><article><span class="stat-icon green"><Eye :size="20" /></span><div><p>Cursos publicados</p><strong>{{ publishedCount }}</strong><small>visíveis no site</small></div></article><article><span class="stat-icon amber"><Star :size="20" /></span><div><p>Em destaque</p><strong>{{ featuredCount }}</strong><small>na página inicial</small></div></article><article><span class="stat-icon purple"><WhatsAppIcon /></span><div><p>Cliques WhatsApp</p><strong>{{ clicks?.summary.total_clicks || 0 }}</strong><small>nos últimos 30 dias</small></div></article></section><section class="admin-dashboard-grid"><article class="admin-card"><div class="card-heading"><div><h2>Cursos recentes</h2><p>Últimas atualizações no catálogo.</p></div><RouterLink class="inline-link" :to="{ name: 'admin-courses' }">Ver todos <ArrowRight :size="16" /></RouterLink></div><div class="dashboard-list"><RouterLink v-for="course in courses.slice(0, 5)" :key="course.id" :to="{ name: 'admin-course-edit', params: { id: course.id } }"><div class="course-thumb"><img v-if="course.cover_image_path" :src="course.cover_image_path" alt="" /><GraduationCap v-else :size="18" /></div><div><strong>{{ course.name }}</strong><span>{{ course.category?.name || 'Sem categoria' }}</span></div><em :class="course.is_published ? 'published' : 'draft'">{{ course.is_published ? 'Publicado' : 'Rascunho' }}</em></RouterLink></div></article><article class="admin-card"><div class="card-heading"><div><h2>Atendimentos</h2><p>Cliques recentes de WhatsApp.</p></div><RouterLink class="inline-link" :to="{ name: 'admin-attendances' }">Ver detalhes <ArrowRight :size="16" /></RouterLink></div><AdminState v-if="!clicks?.clicks?.data?.length" type="empty" message="Os registros aparecerão quando alguém clicar nos CTAs do WhatsApp." /><div v-else class="dashboard-list"><div v-for="click in clicks.clicks.data" :key="click.id"><span class="circle-icon"><WhatsAppIcon :size="16" /></span><div><strong>{{ click.course || 'Curso não identificado' }}</strong><span>{{ click.modality || 'Modalidade não informada' }}</span></div><time>{{ new Date(click.created_at).toLocaleDateString('pt-BR') }}</time></div></div></article></section></template></template>
